apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  labels:
    app: wisecow
    k8s-app-resource: service
spec:
  selector:
    app: wisecow
    k8s-app-resource: pod
  ports:
    - name: wisecow-port
      port: 4499
      protocol: TCP
  type: ClusterIP
