name: Build and Push Docker Image to Docker Hub and Deploy to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERFILE_PATH: ./Dockerfile
  IMAGE_NAME: wisecow
  DOCKER_REPOSITORY: sunnych8790
  CLUSTER_NAME: myaks-cluster
  RESOURCE_GROUP: my_rg
  
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ env.DOCKER_REPOSITORY }}
        password: ${{ secret.DockerhubPassword }}
        
        

    - name: Build Docker Images
      run: |
        echo "Building Docker Image"
        docker build -t ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ${{ env.DOCKERFILE_PATH }} --no-cache
        echo "Image Build Successfully."
        
    - name: Push Docker Images
      run: |
         echo "Pushing Docker Image"
         docker push ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
         echo "Docker Image Pushed Successfully."

  Update-on-AKS:
    needs: build_and_push
    runs-on: ubuntu:latest
    name: Update the deployment
    steps:
      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
      - name: Modify the Deployment file
        run: |
          echo "Updateing image in Deployment file"
          sed -i "s|image: .*/wisecow:.*|image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" wisecow_deployment.yaml
          
      - name: Deploy to Kubernetes clsuter
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: wisecow_deployment.yaml
  
